# Generated by Django 5.2.6 on 2025-09-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseRegistration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(default="", upload_to="news_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="published_date",
            field=models.DateField(),
        ),
    ]
