# Generated by Django 5.2 on 2025-09-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SliderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.ImageField(upload_to="slider_images/")),
                ("heading", models.CharField(max_length=200)),
                ("subheading", models.CharField(max_length=300)),
            ],
        ),
    ]
